server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  datasource:
    password: password123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_aoyama?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false